# Generated by Django 4.0.4 on 2022-05-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_id', models.IntegerField(db_index=True, unique=True, verbose_name='Issue ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('number', models.IntegerField(null=True, verbose_name='Number')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('assignee', models.CharField(max_length=120, null=True, verbose_name='Assignee')),
                ('state', models.CharField(max_length=255, verbose_name='State')),
                ('created_at', models.DateTimeField(help_text='Date when issue was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(help_text='Date when issue was modified', null=True, verbose_name='Updated At')),
                ('closed_at', models.DateTimeField(help_text='Date when issue was closed', null=True, verbose_name='Closed At')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
