# Generated by Django 4.0.4 on 2022-05-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Issues', '0002_remove_issues_assignee_remove_issues_label_labels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignees',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='labels',
            name='reference_id',
        ),
    ]
